name: Publish package

on:
    workflow_dispatch:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: write        
        steps:
        - name: Checkout
          uses: actions/checkout@master
          with:
            path: main
        
        - name: Checkout base torillic
          uses: actions/checkout@v3
          with:
            repository: TEParsons/torillic
            ref: split
            path: base
        
        - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
        
        - name: Inject base Torillic
          run: |
            python base/utils/stub.py
        
        - name: Compress to .zip
          run: |
            cd main/torillic
            zip -r torillic.zip .
            cd ../..
          
        - name: Commit build
          run: |
            cd main
            git config --global user.email "todd.e.parsons@googlemail.com"
            git config --global user.name "Todd Parsons"
            git add --all
            git commit --all -m "sys: Build for release"
        
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: build
            force: true
            directory: ./main
        
        - name: Release - Push changes
          if: startsWith(github.ref, 'refs/tags/')
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: last-release
            force: true
            directory: ./main
        
        - name: Release - Get info
          if: startsWith(github.ref, 'refs/tags/')
          id: release
          uses: cardinalby/git-get-release-action@1.2.4
          with:
            tag: ${{ github.ref_name }}
          
        - name: Release - Update binaries
          if: startsWith(github.ref, 'refs/tags/')
          uses: actions/upload-release-asset@main
          with:
            upload_url: ${{ steps.release.outputs.upload_url }}
            asset_path: main/torillic/torillic.zip
            asset_name: torillic.zip
            asset_content_type: application/zip
